### ISSUE TITLE
Move constants to a dedicated constants file

### ISSUE THREAD

**Issue by smophat7** [beanlab/vs-code-ai-extension#19]
Currently, there are some constants at the top of src/extension.ts but that list will grow and should be moved to its own file and follow proper TypeScript naming conventions.

**Comment by EianWright** [comment]
I'm going to expand the scope of this issue a bit to include just generally pulling code out of `src/extension.ts` into separate files. We want to follow a good separation of concerns so that `src/extension.ts` doesn't become extremely long and bloated.
