### ISSUE TITLE
Define JSON Schemas for CompletionModel interface

### ISSUE THREAD

**Issue by byubean** [beanlab/vs-code-ai-extension#6]
The `CompletionModel` interface abstracts a given AI completion service. 

We need to define the structure of the necessary information that a given implementation of `CompletionModel` will transform to a specific API requirement (e.g. ChatGPT API). 

- First look at API JSON schemas for OpenAI, Bard, LLama, open source option?  
  - Big question: is there enough similarity that we can create a universal abstraction on the "completion request" idea?
- Define the schema for input and output from `CompletionModel` (or define a type)

**Comment by EianWright** [comment]
I tried to look at the API for Bard and LLama.

Bard doesn't have any public documentation for its API as of yet. It seems to be locked behind an invite only program. I signed up for the waitlist to access it when it becomes available.

The API for LLama is also in the same state, but they do have some public documentation on it. It seems to be following the same idea as GPT's API. The messages contain a role and a content. It even has some other parameters that are very similar to GPT's API. Currently, it appears that they only have a Python library availble. Hopefully in the future, there is a JavaScript package or just an endpoint available.
